### ISSUE TITLE
Реализовать стандартное API ISS MOEX

### ISSUE THREAD

**Issue by ArtMan-8** [ArtMan-8/moex-iss-api#4]
# Стандартные запросы к ISS MOEX

:briefcase: - запросы доступны только [подписчикам MOEX](https://www.moex.com/ru/orders)

## Различная информация

- [x] Глобальные справочники ISS
[/iss/index](http://iss.moex.com/iss/reference/28)

- [x] #5
[/iss/events](http://iss.moex.com/iss/reference/193)
[/iss/events/[event_id]](http://iss.moex.com/iss/reference/194)

- [x] #6
[/iss/sitenews](http://iss.moex.com/iss/reference/191)
[/iss/sitenews/[news_id]](http://iss.moex.com/iss/reference/192)

<br />

- [x] #7
[/iss/turnovers](http://iss.moex.com/iss/reference/24)
   - [x] Описание полей для запросов оборотов по рынку/торговой системе
[/iss/turnovers/columns](http://iss.moex.com/iss/reference/100)

<br />

- [ ] :briefcase: Индикаторы риска
[/iss/rms/engines/[engine]/objects/irr](http://iss.moex.com/iss/reference/764)
   - [ ] :briefcase: Доступные параметры фильтрации для индикаторов рисков
[/iss/rms/engines/[engine]/objects/irr/filters](http://iss.moex.com/iss/reference/766)

## Информация по торговым системам и рынкам

- [ ] Доступные торговые системы 
[/iss/engines](http://iss.moex.com/iss/reference/40)
- [ ] Описание и режим работы торговой системы
[/iss/engines/[engine]](http://iss.moex.com/iss/reference/41)
- [ ] Список рынков торговой системы
[/iss/engines/[engine]/markets](http://iss.moex.com/iss/reference/42)
- [ ] Доступные режимы торгов, описание полей публикуемых таблиц данных и т.д. 
[/iss/engines/[engine]/markets/[market]](http://iss.moex.com/iss/reference/44)
- [ ] Таблица инструментов торговой сессии по рынку в целом 
[/iss/engines/[engine]/markets/[market]/securities](http://iss.moex.com/iss/reference/33)

<br />

- [ ] Описание полей для запросов стакана котировок для рынка
[/iss/engines/[engine]/markets/[market]/.*?orderbook/columns](http://iss.moex.com/iss/reference/98)
- [ ] Описание полей для запросов публикуемых бумаг для рынка
[/iss/engines/[engine]/markets/[market]/.*?securities/columns](http://iss.moex.com/iss/reference/99)
- [ ] Описание полей для запроса сделок по рынку
[/iss/engines/[engine]/markets/[market]/.*?trades/columns](http://iss.moex.com/iss/reference/97)

<br />

- [ ] Текущее значение оборотов торговой сессии по рынкам торговой системы 
[/iss/engines/[engine]/turnovers](http://iss.moex.com/iss/reference/95)
- [ ] Текущее значение оборота по рынку
[/iss/engines/[engine]/markets/[market]/turnovers](http://iss.moex.com/iss/reference/96)
- [ ] Все сделки рынка 
[/iss/engines/[engine]/markets/[market]/trades](http://iss.moex.com/iss/reference/35)
- [ ] Стаканы заявок всех инструментов рынка
[/iss/engines/[engine]/markets/[market]/orderbook](http://iss.moex.com/iss/reference/36)
- [ ] Промежуточные итоги дня
[/iss/engines/[engine]/markets/[market]/secstats](http://iss.moex.com/iss/reference/823)
- [ ] Кривая бескупонной доходности государственных облигаций
[/iss/engines/[engine]/zcyc](http://iss.moex.com/iss/reference/634)

### Информация по конкретному инструменту

- [ ] Данные по конкретному инструменту рынка
[/iss/engines/[engine]/markets/[market]/securities/[security]](http://iss.moex.com/iss/reference/52)
- [ ] Интервалы, для которых есть данные по свечкам
[/iss/engines/[engine]/markets/[market]/securities/[security]/candleborders](http://iss.moex.com/iss/reference/156)
- [ ] Свечи указанного инструмента по дефолтной группе режимов
[/iss/engines/[engine]/markets/[market]/securities/[security]/candles](http://iss.moex.com/iss/reference/155)
- [ ] Стакан заявок по инструменту
[/iss/engines/[engine]/markets/[market]/securities/[security]/orderbook](http://iss.moex.com/iss/reference/54)
- [ ] #40
[/iss/engines/[engine]/markets/[market]/securities/[security]/trades](http://iss.moex.com/iss/reference/55)

### Информация по режиму торгов

- [ ] Справочник режимов торгов рынка
[/iss/engines/[engine]/markets/[market]/boards](http://iss.moex.com/iss/reference/43)
- [ ] Описание режима торгов 
[/iss/engines/[engine]/markets/[market]/boards/[board]](http://iss.moex.com/iss/reference/49)
- [ ] Все сделки по выбранному режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/trades](http://iss.moex.com/iss/reference/34)
- [ ] Все лучшие котировки по выбранному режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/orderbook](http://iss.moex.com/iss/reference/39)
- [ ] Таблица инструментов по режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities](http://iss.moex.com/iss/reference/32)
- [ ] Данные по указанному инструменту на выбранном режиме торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities/[security]](http://iss.moex.com/iss/reference/53)
- [ ] Период дат рассчитанных свечей
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities/[security]/candleborders](http://iss.moex.com/iss/reference/48)
- [ ] Свечи указанного инструмента по выбранному режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities/[security]/candles](http://iss.moex.com/iss/reference/46)
- [ ] Стакан котировок указанного инструмента по выбранному режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities/[security]/orderbook](http://iss.moex.com/iss/reference/57)
- [ ] Все сделки указанного инструмента по выбранному режиму торгов
[/iss/engines/[engine]/markets/[market]/boards/[board]/securities/[security]/trades](http://iss.moex.com/iss/reference/56)

### Информация по группам режимов торгов

- [ ] Справочник групп режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups](http://iss.moex.com/iss/reference/45)
- [ ] Описание группы режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]](http://iss.moex.com/iss/reference/50)
- [ ] Сделки инструментов, торгуемых на выбранной группе режимов торгов 
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/trades](http://iss.moex.com/iss/reference/37)
- [ ] Лучшие заявки всех инструментов, торгуемых на выбранной группе режимов торгов 
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/orderbook](http://iss.moex.com/iss/reference/38)
- [ ] Список всех инструментов, торгуемых на выбранной группе режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities](http://iss.moex.com/iss/reference/29)
- [ ] Данные по указанному инструменту, торгуемому на выбранной группе режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]](http://iss.moex.com/iss/reference/58)
- [ ] Период дат рассчитанных свечей
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]/candleborders](http://iss.moex.com/iss/reference/158)
- [ ] Свечи указанного инструмента по выбранной группе режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]/candles](http://iss.moex.com/iss/reference/157)
- [ ] Лучшие заявки выбранного инструмента, торгуемого на выбранной группе режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]/orderbook](http://iss.moex.com/iss/reference/59)
- [ ] Сделки выбранного инструмента, торгуемого на выбранной группе режимов торгов
[/iss/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]/trades](http://iss.moex.com/iss/reference/60)

## Информация по торгуемым инструментам

- [x] #23
[/iss/securities](http://iss.moex.com/iss/reference/5)
- [x] #24
[/iss/securities/[security]](http://iss.moex.com/iss/reference/13)
- [x] #25
[/iss/securities/[security]/indices](http://iss.moex.com/iss/reference/160)
- [x] #26
[/iss/securities/[security]/aggregates](http://iss.moex.com/iss/reference/214)

<br />

- [x] #14
[/iss/securitygroups](http://iss.moex.com/iss/reference/127)
- [x] #15
[/iss/securitygroups/[securitygroup]](http://iss.moex.com/iss/reference/128)

<br />

- [x] #19
[/iss/securitygroups/[securitygroup]/collections](http://iss.moex.com/iss/reference/129)
- [x] #20
[/iss/securitygroups/[securitygroup]/collections/[collection]](http://iss.moex.com/iss/reference/130)
- [x] #21
[/iss/securitygroups/[securitygroup]/collections/[collection]/securities](http://iss.moex.com/iss/reference/131)

<br />

- [x] #16
[/iss/securitytypes](http://iss.moex.com/iss/reference/132)
- [x] #17
[/iss/securitytypes/[securitytype]](http://iss.moex.com/iss/reference/133)

## Аналитика

- [x] #9
[/iss/analyticalproducts/curves/securities](http://iss.moex.com/iss/reference/859)
[/iss/analyticalproducts/curves/securities/[security]](http://iss.moex.com/iss/reference/861)

- [ ] #10
[/iss/analyticalproducts/futoi/securities](http://iss.moex.com/iss/reference/807)
[/iss/analyticalproducts/futoi/securities/[security]](http://iss.moex.com/iss/reference/809)
💼 - за последние 2 недели

- [ ] #11
[/iss/analyticalproducts/netflow2/securities](http://iss.moex.com/iss/reference/767)
[/iss/analyticalproducts/netflow2/securities/[security]](http://iss.moex.com/iss/reference/769)
💼 - за последние 2 недели

## Исторические данные

- [ ] Информация по техническому изменению торговых кодов
[/iss/history/engines/stock/markets/shares/securities/changeover](http://iss.moex.com/iss/reference/123)
- [ ] История изменения параметров Кривой Бескупоной Доходности
[/iss/history/engines/stock/zcyc](http://iss.moex.com/iss/reference/783)

<br />

- [ ] Список режимов обобщенной информации по фондовому рынку
[/iss/history/engines/stock/totals/boards](http://iss.moex.com/iss/reference/161)
- [ ] Обобщенная информация по фондовому рынку по выбранному режиму
[/iss/history/engines/stock/totals/boards/[board]/securities](http://iss.moex.com/iss/reference/163)
- [ ] Обобщенная информация по фондовому рынку по выбранному режиму и инструменту
[/iss/history/engines/stock/totals/boards/[board]/securities/[security]](http://iss.moex.com/iss/reference/164)
- [ ] Обобщенная информация по фондовому рынку по выбранному режиму
[/iss/history/engines/stock/totals/securities](http://iss.moex.com/iss/reference/162)

<br />

- [ ] Обобщенные данные ОТС ПФИ и РЕПО - список рынков
[/iss/history/otc/providers/nsd/markets](http://iss.moex.com/iss/reference/833)
- [ ] Ежедневные обобщенные данные ОТС ПФИ и РЕПО
[/iss/history/otc/providers/nsd/markets/[market]/daily](http://iss.moex.com/iss/reference/835)
- [ ] Ежедневные обобщенные данные ОТС ПФИ и РЕПО
[/iss/history/otc/providers/nsd/markets/[market]/monthly](http://iss.moex.com/iss/reference/837)

<br />

- [ ] Ежедневные обобщенные данные ОТС ПФИ и РЕПО
[/iss/history/engines/[engine]/markets/[market]/dates](http://iss.moex.com/iss/reference/83)
- [ ] Список неторгуемых инструментов с указанием интервалов торгуемости по режимам
[/iss/history/engines/[engine]/markets/[market]/listing](http://iss.moex.com/iss/reference/118)

<br />

- [ ] Описание полей для запросов исторических данных по бумагам для рынка
[/iss/history/engines/[engine]/markets/[market]/.*?[securities]/columns](http://iss.moex.com/iss/reference/789)
- [ ] Описание полей для запросов торгуемости бумаг
[/iss/history/engines/[engine]/markets/[market]/.*?listing/columns](http://iss.moex.com/iss/reference/117)
- [ ] Описание полей для запросов исторических данных по бумагам для рынка
[/iss/history/engines/[engine]/markets/[market]/.*?securities/columns](http://iss.moex.com/iss/reference/101)

<br />

- [ ] История рассчитанных доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате
[/iss/history/engines/[engine]/markets/[market]/yields](http://iss.moex.com/iss/reference/791)
- [ ] Историю доходностей по одной бумаге на рынке за интервал дат
[/iss/history/engines/[engine]/markets/[market]/yields/[security]](http://iss.moex.com/iss/reference/793)

<br />

- [ ] История торгов для всех бумаг на указанной группе режимов торгов за указанную дату
[/iss/history/engines/[engine]/markets/[market]/session/[session]/boardgroups/[boardgroup]/securities](http://iss.moex.com/iss/reference/825)
- [ ] История по всем бумагам на рынке за одну дату
[/iss/history/engines/[engine]/markets/[market]/securities](http://iss.moex.com/iss/reference/62)
- [ ] Историю по одной бумаге на рынке за интервал дат
[/iss/history/engines/[engine]/markets/[market]/securities/[security]](http://iss.moex.com/iss/reference/63)
- [ ] Интервал дат в истории для указанного рынка и бумаги
[/iss/history/engines/[engine]/markets/[market]/securities/[security]/dates](http://iss.moex.com/iss/reference/61)

### История по торгуемым инструментам

- [ ] Список сессий доступных в итогах торгов. Только для фондового рынка!
[/iss/history/engines/[engine]/markets/[market]/sessions](http://iss.moex.com/iss/reference/811)
- [ ] История торгов для указанной бумаги на выбранной группе режимов торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/sessions/[session]/boardgroups/[boardgroup]/securities/[security]](http://iss.moex.com/iss/reference/819)
- [ ] История торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате
[/iss/history/engines/[engine]/markets/[market]/sessions/[session]/boards/[board]/securities](http://iss.moex.com/iss/reference/821)
- [ ] История торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/sessions/[session]/boards/[board]/securities/[security]](http://iss.moex.com/iss/reference/815)
- [ ] История по всем бумагам на рынке за одну дату
[/iss/history/engines/[engine]/markets/[market]/sessions/[session]/securities](http://iss.moex.com/iss/reference/813)
- [ ] История по одной бумаге на рынке за интервал дат
[/iss/history/engines/[engine]/markets/[market]/sessions/[session]/securities/[security]](http://iss.moex.com/iss/reference/817)

### История по режиму торгов

- [ ] Интервал дат, доступных в истории для рынка по заданному режиму торгов
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/dates](http://iss.moex.com/iss/reference/26)
- [ ] Данные по листингу бумаг в историческом разрезе по указанному режиму
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/listing](http://iss.moex.com/iss/reference/119)
- [ ] История торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/securities](http://iss.moex.com/iss/reference/64)
- [ ] История торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/securities/[security]](http://iss.moex.com/iss/reference/65)
- [ ] Интервал дат в истории, за которые доступна указанная бумага на рынке на указанном режиме торгов
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/securities/[security]/dates](http://iss.moex.com/iss/reference/66)
- [ ] История доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/yields](http://iss.moex.com/iss/reference/795)
- [ ] История доходностей для указанной бумаги на указанном режиме торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/boards/[board]/yields/[security]](http://iss.moex.com/iss/reference/797)

### История по группам режимов торгов

- [ ] Интервал дат для указанной группы режимов торгов
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/dates](http://iss.moex.com/iss/reference/51)
- [ ] Данные по листингу бумаг в историческом разрезе по указанной группе режимов
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/listing](http://iss.moex.com/iss/reference/120)
- [ ] История аукционов даркпул отфильтрованных по дате
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities](http://iss.moex.com/iss/reference/152)
- [ ] История торгов для всех бумаг на указанной группе режимов торгов за указанную дату
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities](http://iss.moex.com/iss/reference/67)
- [ ] История аукционов даркпул за интервал дат
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]](http://iss.moex.com/iss/reference/153)
- [ ] История торгов для указанной бумаги на выбранной группе режимов торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]](http://iss.moex.com/iss/reference/68)
- [ ] Интервал дат для указанной бумаги на заданной группе режимов торгов
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/securities/[security]/dates](http://iss.moex.com/iss/reference/69)
- [ ] Доходности торгов для всех бумаг на указанной группе режимов торгов за указанную дату
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/yields](http://iss.moex.com/iss/reference/799)
- [ ] История доходностей для указанной бумаги на выбранной группе режимов торгов за указанный интервал дат
[/iss/history/engines/[engine]/markets/[market]/boardgroups/[boardgroup]/yields/[security]](http://iss.moex.com/iss/reference/801)

## Архивы

- [ ] Получить список ссылок на годовые/месячные/дневные файлы с архивом сделок и исторической биржевой информацией 
[/iss/archives/engines/[engine]/markets/[market]/[datatype]/[period]](http://iss.moex.com/iss/reference/116)

- [ ] Список годов, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией 
[/iss/archives/engines/[engine]/markets/[market]/[datatype]/years](http://iss.moex.com/iss/reference/114)

- [ ] Список месяцев в году, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией
[/iss/archives/engines/[engine]/markets/[market]/[datatype]/years/[year]/months](http://iss.moex.com/iss/reference/115)

## Статисктика

- [ ] Курсы ЦБРФ
[/iss/statistics/engines/currency/markets/selt/rates](http://iss.moex.com/iss/reference/168)

<br />

- [ ] Ставки по операциям центрального банка
[/iss/statistics/engines/state/markets/repo/cboper](http://iss.moex.com/iss/reference/169)
[/iss/statistics/engines/state/markets/repo/dealers](http://iss.moex.com/iss/reference/166)
[/iss/statistics/engines/state/markets/repo/mirp](http://iss.moex.com/iss/reference/165)

<br />

- [ ] Ставки по аукционам Банка России
[/iss/statistics/engines/state/rates](http://iss.moex.com/iss/reference/178)
[/iss/statistics/engines/state/rates/columns](http://iss.moex.com/iss/reference/179)

<br />

- [ ] Курсы переоценки коллатеральных инструментов
[/iss/statistics/engines/[engine]/markets/[market]](http://iss.moex.com/iss/reference/771)
[/iss/statistics/engines/[engine]/markets/[market]/securities](http://iss.moex.com/iss/reference/773)
[/iss/statistics/engines/[engine]/markets/[market]/securities/[security]](http://iss.moex.com/iss/reference/775)

<br />

- [ ] Индикативные курсы валют срочного рынка
[/iss/statistics/engines/futures/markets/indicativerates/securities](http://iss.moex.com/iss/reference/711)
- [ ] Индикативный курс валют срочного рынка
[/iss/statistics/engines/futures/markets/indicativerates/securities/[security]](http://iss.moex.com/iss/reference/712)

<br />

- [ ] Еженедельные отчеты по валютным деривативам
[/iss/statistics/engines/[engine]/derivatives/[report_name]](http://iss.moex.com/iss/reference/219)
[/iss/statistics/engines/[engine]/monthly/[report_name]](http://iss.moex.com/iss/reference/220)

<br />

- [ ] Фиксинги Московской биржи
[/iss/statistics/engines/currency/markets/fixing](http://iss.moex.com/iss/reference/716)
[/iss/statistics/engines/currency/markets/fixing/[security]](http://iss.moex.com/iss/reference/715)

<br />

- [ ] Капитализация фондового рынка
[/iss/statistics/engines/stock/capitalization](http://iss.moex.com/iss/reference/159)

- [ ] Текущие цены бумаг
[/iss/statistics/engines/stock/currentprices](http://iss.moex.com/iss/reference/649)

- [ ] Показатели для определения критериев существенного отклонения
[/iss/statistics/engines/stock/deviationcoeffs](http://iss.moex.com/iss/reference/134)

<br />

- [ ] Агрегированные показатели рынка облигаций
[/iss/statistics/engines/stock/markets/bonds/aggregates](http://iss.moex.com/iss/reference/195)
[/iss/statistics/engines/stock/markets/bonds/aggregates/columns](http://iss.moex.com/iss/reference/196)

<br />

- [ ] Cписок акций, по которым рассчитывается рыночная котировка 
[/iss/statistics/engines/stock/quotedsecurities](http://iss.moex.com/iss/reference/171)

- [ ] Таблица соответствия торгуемых ценных бумаг по режимам торгов
[/iss/statistics/engines/stock/securitieslisting](http://iss.moex.com/iss/reference/841)

- [ ] Бюллетени для индексов
[/iss/statistics/engines/stock/markets/index/bulletins](http://iss.moex.com/iss/reference/839)

- [ ] RUSFAR(справедливая стоимость денег) расшифровка показателей
[/iss/statistics/engines/stock/markets/index/rusfar](http://iss.moex.com/iss/reference/843)

- [ ] Коэффициенты корелляции фондового рынка
[/iss/statistics/engines/stock/markets/shares/correlations](http://iss.moex.com/iss/reference/172)

- [ ] Справочник дроблений и консолидаций бумаг фондового рынка
[/iss/statistics/engines/stock/splits](http://iss.moex.com/iss/reference/758)
[/iss/statistics/engines/stock/splits/[security]](http://iss.moex.com/iss/reference/759)

<br />

- [ ] Индексы фондового рынка
[/iss/statistics/engines/stock/markets/index/analytics](http://iss.moex.com/iss/reference/146)
[/iss/statistics/engines/stock/markets/index/analytics/columns](http://iss.moex.com/iss/reference/205)
- [ ] Аналитические показатели за дату
[/iss/statistics/engines/stock/markets/index/analytics/[indexid]](http://iss.moex.com/iss/reference/147)
- [ ] Список тикеров за все время торгов
[/iss/statistics/engines/stock/markets/index/analytics/[indexid]/tickers](http://iss.moex.com/iss/reference/148)
- [ ] Информация по тикеру
[/iss/statistics/engines/stock/markets/index/analytics/[indexid]/tickers/[ticker]](http://iss.moex.com/iss/reference/149)
